<div class="container-fluid">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="img-responsive d-block w-100" src="<?php echo $this->getSkinUrl('images/custom/1.jpg') ?>" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="img-responsive  d-block w-100" src="<?php echo $this->getSkinUrl('images/custom/2.jpg') ?>" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="img-responsive  d-block w-100" src="<?php echo $this->getSkinUrl('images/custom/3.jpg') ?>" alt="Third slide">
            </div>
            <div class="carousel-item">
                <img class="img-responsive  d-block w-100" src="<?php echo $this->getSkinUrl('images/custom/4.jpg') ?>" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div><!------------------------container-Fluid--->


<div class="my-inner-content">
    <div class="col-md-10 col-xs-12 offset-md-1 my-content-inner">
        <div class="servicesss col-md-12 text-center" >
            <div class="services col-md-3 col-xs-12" style="background:rgba(0,0,0,0.7); ">
                <h4 class="text-left" style="padding-bottom:3%!important;"><img src="<?php echo $this->getSkinUrl('images/custom/title-arrow-red.png') ?>">&nbsp;Super Savers</h4>
                <p>Lorem ipsum Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsum</p>
                <div class="personalise">
                    <button class="my-button text-left"><a href="<?php echo $this->getUrl('') ?>super-savers.html">Shop now</a><img src="<?php echo $this->getSkinUrl('images/custom/btn-right-arr.png') ?>"></button>
                    <img class="personalise-img img-responsive mx-auto" style="width:30%;" src="<?php echo $this->getSkinUrl('images/custom/Personalise.png') ?>">
                </div>
            </div>
            <div class="services col-md-4 offset-md-1 col-xs-12" style="background:rgba(0,0,0,0.7);">
                <h4 class="text-left" style="padding-bottom:3%!important;"><img src="<?php echo $this->getSkinUrl('images/custom/title-arrow-red.png') ?>">&nbsp;Bundle Offers</h4>
                <p>Lorem ipsum Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsum</p>
                <div class="personalise1">
                    <button class="my-button text-left"><a href="<?php echo $this->getUrl('') ?>bundle-offers.html">Shop now</a><img src="<?php echo $this->getSkinUrl('images/custom/btn-right-arr.png') ?>"></button>
                    <img class="personalise-img img-responsive mx-auto" style="width:75%;" src="<?php echo $this->getSkinUrl('images/custom/newarrivals.png') ?>">
                </div>
            </div>
            <div class="services col-md-3 offset-md-1 col-xs-12" style="background:rgba(0,0,0,0.7);">
                <h4 class="text-left" style="padding-bottom:3%!important;"><img src="<?php echo $this->getSkinUrl('images/custom/title-arrow-red.png') ?>">&nbsp;Accessories</h4>
                <p>Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsum</p>
                <div class="personalise">
                    <button class="my-button text-left"><a href="<?php echo $this->getUrl('') ?>accessories.html">Shop now</a><img src="<?php echo $this->getSkinUrl('images/custom/btn-right-arr.png') ?>"></button>
                    <img class="personalise-img img-responsive mx-auto" style="width:50%;" src="<?php echo $this->getSkinUrl('images/custom/accessories.png') ?>">
                </div>
            </div>
        </div>
    </div>
</div>