<div class="inner-banner"><img src="<?php echo $this->getSkinUrl('images/banner.jpg'); ?>" /></div>
<?php if($this->canShowBlock()): ?>
<div class="filter-wrapper">
<div class="block block-layered-nav">
    <div class="block-content">
        <?php echo $this->getStateHtml() ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
        <?php if($this->canShowOptions()): ?>
        <div class="filterss">
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount()): ?>
                <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"><?php echo $this->__($_filter->getName()) ?>
                    <span class="caret"></span></button>
                    <?php echo $_filter->getHtml() ?>
                </div>
                <?php endif; ?>
                <?php endforeach; ?>
        </div>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
            <script type="text/javascript">
                jQuery(function($){
                    $(".block-layered-nav dt").click(function(){
                        if($(this).next("dd").css("display") == "none"){
                            $(this).next("dd").slideDown(200);
                            $(this).removeClass("closed");
                        } else {
                            $(this).next("dd").slideUp(200);
                            $(this).addClass("closed");
                        }
                    });
                });
            </script>
        <?php endif; ?>
    </div>
</div>
</div>
<?php endif; ?>
