<?php
$store = Mage::app()->getStore();
$code = $store->getCode();
$enabled = Mage::getStoreConfig('homeslider/general/enabled', $code);
$type = Mage::getStoreConfig('homeslider/general/type', $code);
$static_block_id = Mage::getStoreConfig('homeslider/general/static_block_id', $code);
if($enabled == 1){
?>
<div id="slideshow" style="background-color: #000;">

<?php
    echo $this->getLayout()->createBlock('cms/block')->setBlockId($static_block_id)->toHtml();
?>

    <div class="banner-overlay">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="borderBox">
                        <div class="innerBox">
                            <h4><i class="icon-arrow"></i><?php echo $this->__('Super Savers') ?></h4>
                            <p><?php echo $this->__('Enjoy special discounts on selected Zippo Lighter models at unmatched prices. Start collection now...') ?> <a href="<?php echo $this->getUrl('') ?>super-savers.html"><?php echo $this->__('Shop Now') ?></a> </p>
                            <div class="shopNow_wrapper"><a href="<?php echo $this->getUrl('') ?>super-savers.html"">Shop Now <img src="<?php echo $this->getSkinUrl('images/btn-right-arr.png'); ?>"></a><img src="<?php echo $this->getSkinUrl('images/1.png'); ?>"></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="borderBox">
                        <div class="innerBox">
                            <h4><?php echo $this->__('New Arrivals') ?></h4>
                            <p><?php echo $this->__('Browse new finishes & engraving combination!Our new arrivals include: Superb Armor lighters with 360-degree MultiCut, Laser & Auto Engrave combination imprints...') ?> <a href="<?php echo $this->getUrl('') ?>new-arrivals.html"><?php echo $this->__('Shop Now') ?></a> </p>
                            <div class="shopNow_wrapper"><a href="<?php echo $this->getUrl('') ?>new-arrivals.html"">Shop Now <img src="<?php echo $this->getSkinUrl('images/btn-right-arr.png'); ?>"></a><img src="<?php echo $this->getSkinUrl('images/2.png'); ?>"></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="borderBox">
                        <div class="innerBox">
                            <h4><?php echo $this->__('Bundle Offers') ?></h4>
                            <p><?php echo $this->__('Enjoy Great Deals on selective Zippo lighter models with Zippo accessories bundled together to add value to your purchases...') ?> <a href="<?php echo $this->getUrl('') ?>bundle-offers.html"><?php echo $this->__('Shop Now') ?></a> </p>
                            <div class="shopNow_wrapper"><a href="<?php echo $this->getUrl('') ?>bundle-offers.html">Shop Now <img src="<?php echo $this->getSkinUrl('images/btn-right-arr.png'); ?>"></a><img src="<?php echo $this->getSkinUrl('images/3.png'); ?>"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php    
} else {
?>
<?php
}
?>